### ISSUE TITLE
Issue while catching exceptions and creating custom error object

### ISSUE THREAD

**Issue by SwatiSingh9191** [koorchik/node-mole-rpc#5]
Hi, I am using mole-rpc to utilize the MQTT transport to get responses from ConMan( a network manager). 
**Issue :** My issue is when there is an excpetion in my application then conman  sends this error message on the MQTT topic. eg. {code: -32603, message: "Server error", data: "Invalid arguments"}
The problem occurs when, conman sends an errorcode other than **-32601 i.e METHOD_NOT_FOUND** as seen in the example above. One of the functions **_makeErrorObject()** in **MoleClient.js** fails with an Exception : 

_Thu, 05 Dec 2019 09:49:42 GMT uncaughtException: errorBuilder is not a function
TypeError: errorBuilder is not a function
    at MoleClient._makeErrorObject (C:\xaap-web-ui\gateway-master-git\gateway\backend\node_modules\mole-rpc\MoleClient.js:191:16)
    at MoleClient._processSingleCallResponse (C:\xaap-web-ui\gateway-master-git\gateway\backend\node_modules\mole-rpc\MoleClient.js:103:38)
    at MoleClient._processResponse (C:\xaap-web-ui\gateway-master-git\gateway\backend\node_modules\mole-rpc\MoleClient.js:85:18)
    at MqttClient.mqttClient.on (C:\xaap-web-ui\gateway-master-git\gateway\backend\node_modules\mole-rpc-transport-mqtt\TransportClient.js:17:13).....more_

`makeErrorObject(errorData) {
        const errorBuilder = {
            [errorCodes.METHOD_NOT_FOUND]: () => {
                return new X.MethodNotFound();
            }
        }[errorData.code];

        return errorBuilder();
    }`

The reason for this behaviour is that this method always tries to map all the exceptions to a custom error object and particularly to error code **-32601**, **METHOD_NOT_FOUND** 

Can this method be modified to handle all the error codes included in the **errorCodes.js and X.js files**.
`module.exports = {
    PARSE_ERROR: -32700,
    INVALID_REQUEST: -32600,
    METHOD_NOT_FOUND: -32601,
    INVALID_PARAMS: -32602,
    INTERNAL_ERROR: -32603
};
`
Any response on this would be really appreciated.

**Comment by koorchik** [comment]
Hi, thank you. Should work in version 1.0.0. I've added several examples to the docs. Could you recheck whether it solves the issue - https://www.npmjs.com/package/mole-rpc#error-handling

**Comment by yoursunny** [comment]
This bug is not fixed in the release, but #14 fixes the bug.

**Comment by larsschwegmann** [comment]
I am facing the same issue. Is there any update on this? @koorchik is this project still maintained? Could you merge #14 ?
